### ISSUE TITLE
Starting OFraMP from ATB fails

### ISSUE THREAD

**Issue by enitram** [bertrand-caron/OFraMP#5]
starting OFraMP from the ATB fails with 'Invalid data'

**Comment by enitram** [comment]
![screenshot from 2018-01-11 08-28-18](https://user-images.githubusercontent.com/21896334/34813229-6ce87088-f6a9-11e7-9b66-5c9473b24d59.png)

**Comment by enitram** [comment]
http://fragments.atb.uq.edu.au/oframp/?user_token=k2gyxu0j6fzx19r8&atb_id=298300&shell_size=2&repo=qm_1_and_2_full

**Comment by bertrand-caron** [comment]
Any reason you closed it? It's still happening to you. For instance, see [1]

[1]: http://fragments.atb.uq.edu.au/oframp/?user_token=k2gyxu0j6fzx19r8&atb_id=298300&shell_size=2&repo=qm_1_and_2_full

**Comment by bertrand-caron** [comment]
So, I dug a bit deeper in OAPOC to understand this problem. It is caused by bonds identified by Babel in mol2 which are not in the original PDB. For now I have chosen to just ignore those bonds, but it seems Babel is doing a terrible job at assigning bond orders (compare the two graphs below), so I wonder if something very wrong is happening.

# ATB (Babel)
![screen shot 2018-01-12 at 10 48 34 am](https://user-images.githubusercontent.com/4724439/34854501-cd294ecc-f785-11e7-8032-ab40f84af89c.png)

# OAPOC (Babel?)
![screen shot 2018-01-12 at 10 48 27 am](https://user-images.githubusercontent.com/4724439/34854504-cf44a27e-f785-11e7-9fd7-d33142495a50.png)

In the meantime I pushed the OAPOC changes live and we can go from there.

**Comment by enitram** [comment]
OK, I thought this issue was caused by something else.
Issue #7 (and possibly also #6) also seems to be caused by babel (in this case, babel adds more atoms).

**Comment by enitram** [comment]
By the way, which ATB ID is that?

**Comment by bertrand-caron** [comment]
It's `298300 `.

**Comment by enitram** [comment]
Moving to the custom obabel 2.4.1 fixed this issue.
![298300](https://user-images.githubusercontent.com/21896334/35290327-35bacb0e-006a-11e8-9cb1-641c8b85b351.png)
